### PR TITLE
Make time unit compatible with udunit whitespace

### LINKED ISSUE #979: Add more robust handling of time units/datetimes
From support ticket:

When time unit contains an extra space, e.g.
```
double time(time) ;
time:units = "days since 1800-1-1 00:00:0.0" ;
```
netCDF-Java throws: `java.lang.IllegalStateException: CoordinateSystem does not have a usable time axis`

CF convention doesn't explicitly say that there only has to be one space, only that it has to be compatible with
udunits, and udunits is capable of reading time with the extra space, so it would be nice for netCDF-Java to support it as well.

### PR DESCRIPTION
**Pull request by mnlerman**
## Description of Changes

Adresses #979 

Handle the following whitespace characters in time unit strings `{" ", "  ", "\t", "\n", "\r", "\f"}` 

## PR Checklist

- [x] Link to any issues that the PR addresses
- [x] Add labels
- [x] Open as a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/)
       until ready for review
- [x] Make sure GitHub tests pass
- [x] Mark PR as "Ready for Review"

### CODE REVIEW

File: cdm/core/src/test/java/ucar/nc2/time/TestCalendars.java [hunk 1]
```diff
@@ -148,6 +148,23 @@ public void testZeroYear() {
...
+    String[] udunitsWhitespace = new String[] {" ", "  ", "\t", "\n", "\r", "\f"};
+    for (Calendar cal : Calendar.values()) {
+      // unit with time in ISO format to use for testing
+      CalendarDateUnit isoFormatUnit =
+          CalendarDateUnit.withCalendar(cal, String.format("secs since %sT%s", date, time));
+
+      for (String whitespace : udunitsWhitespace) {
+        CalendarDateUnit testUnit =
+            CalendarDateUnit.withCalendar(cal, String.format("secs since %s%s%s", date, whitespace, time));
+        assert (isoFormatUnit.getBaseDate().equals(testUnit.getBaseDate()));
```
Comment (tdrwenski) [inline cdm/core/src/test/java/ucar/nc2/time/TestCalendars.java]: I know all the other tests here are using the built in `asserts` but we would like to eventually have them all use google truth asserts, something like:
```
        assertThat(testUnit.getBaseDate()).isEqualTo(isoFormatUnit.getBaseDate());
```
(you would probably also need to add `import static com.google.common.truth.Truth.assertThat;`)

Comment (mnlerman) [reply cdm/core/src/test/java/ucar/nc2/time/TestCalendars.java]: Got it, thanks! I just updated it and pushed the change

**Review by tdrwenski — APPROVED** [review]

**Comment by haileyajohnson** [comment]
🎉
