### PR TITLE
Correctly handle GINI negative calibration values

### LINKED ISSUE #480: Errors when converting NEXRAD composites (GINI) to netCDF3/netCDF4
When writing a NEXRAD composite GINI file to netCDF the resulting file has incorrect values. I have attached a zip file with the original GINI file as well as the netCDF which resulted from using toolsUI to convert the file to netCDF. Note that the same error occurs when using IDV, or Weather and Climate Toolkit, which all rely on netcdf-java.

[nexrad-gini-samples.zip](https://github.com/Unidata/netcdf-java/files/5226505/nexrad-gini-samples.zip)

The original file is sourced from [a public google cloud storage bucket](https://console.cloud.google.com/storage/browser/gcp-public-data-nexrad-l3-realtime), and the netCDF was inspected using `gdalinfo -stats` using GDAL versions 3.1 & 3.0.

### System Info
* **netcdf-java version**: v5.3.3
* **toolsUI version**: v5.3.3
* **OS**: PopOS 20.04
* **Java version**: OpenJDK 14.0.1
* **Python version**: Python 3.8.2

### PR DESCRIPTION
**Pull request by lesserwhirls**
GINI calibration values can be negative (for the data value range), and GEMPAK uses the left most bit of the stored integer to designate the signedness. Fixes Unidata/netcdf-java#480

Minor addition - since the `long_name` attribute was there and so close, go ahead an add the `standard_name` attribute to the `x` and `y` coordinate variables.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/488)

### CODE REVIEW

File: cdm/image/src/main/java/ucar/nc2/iosp/gini/Giniheader.java [hunk 1]
```diff
@@ -589,10 +596,35 @@ void read(ucar.unidata.io.RandomAccessFile raf, ucar.nc2.NetcdfFile ncfile) thro
...
           int maxb = bos.getInt() / 10000; /* max brightness values */
+
+          // Since these are data values, we need to consider the case of them being positive or negative
+          // Careful though, it's not that easy. Step one is to read the 32-bits like before...
           int mind = bos.getInt(); /* min data values */
+          // Now for the fun.
+          // According to https://github.com/Unidata/gempak/blob/master/gempak/source/gemlib/mv/Linux/mvitob.c,
+          // which is used when writing gini files, if the first bit is set, that indicates that we have a negative
+          // value and need to do a bit more work.
+          // Check if left-most bit is 1. Left shift bit pattern of value 31 times. This will make all bits 0, or
```
Comment (dopplershift) [inline cdm/image/src/main/java/ucar/nc2/iosp/gini/Giniheader.java]: Technically it's a right shift, so it'd be better maybe as: "Right shift by 31 bits".

File: cdm/image/src/main/java/ucar/nc2/iosp/gini/Giniheader.java [hunk 2]
```diff
@@ -589,10 +596,35 @@ void read(ucar.unidata.io.RandomAccessFile raf, ucar.nc2.NetcdfFile ncfile) thro
...
+          // all bits 1. If all 0, then the result will equal zero. If all 1's, then the result will equal -1, and
+          // that's how we know we need to do more work.
+          if ((mind >> 31) == -1) {
+            // Set the first bit to zero, and negate the value (again, described in mvitob.c from gempak)
+            // 0x7FFFFFFF -> left-most bit is zero, all the rest are 1's.
+            // The bit-wise & results in flipping the first bit of "mind" (because we know it is 1 at this point, and
+            // 1 & 0 -> 0) while retaining the rest of the pattern of mind (because 0 & 1 -> 0, 1 & 1 -> 1).
+            // To negate, just use the negative sign...we could do (mind & 0x7FFFFFFF) + 1, but let's not hang out
```
Comment (dopplershift) [inline cdm/image/src/main/java/ucar/nc2/iosp/gini/Giniheader.java]: I don't understand the "+1" bit here

File: cdm/image/src/main/java/ucar/nc2/iosp/gini/Giniheader.java (hunk 1 above)
Comment (lesserwhirls) [reply cdm/image/src/main/java/ucar/nc2/iosp/gini/Giniheader.java]: Yep...pre-coffee typing not recommended. Update incoming.

File: cdm/image/src/main/java/ucar/nc2/iosp/gini/Giniheader.java (hunk 2 above)
Comment (lesserwhirls) [reply cdm/image/src/main/java/ucar/nc2/iosp/gini/Giniheader.java]: Missed the tilde...should be `~(mind & 0x7FFFFFFF) + 1` Update incoming

**Review by dopplershift — APPROVED** [review]
