### PR TITLE
Projection angular coordinates

### LINKED ISSUE #1200: [5.5.4+]: CF 1.9 and Geostationary projection
### Versions impacted by the bug

v5.x

### What went wrong?

The latest CF Convention release (1.10) and apparently the prior release (1.9) now specify that the x and y coordinate variables must have standard_name attributes with values "projection_x_angular_coordinate" and "projection_y_angular_coordinate" rather than the previously specified values of "projection_x_coordinate" and "projection_y_coordinate". This thoroughly messes up using NJ's geostationary projected grid handling.

At first look, it seems that adding a couple more definitions to `ucar.nc2.constants.C`F, and then modifying the if statements in `ucar.nc2.dataset.conv.CF1Convention `and `ucar.nc2.internal.dataset.conv.CF1Convention` that discover the projection x and y axes is sufficient to fix this. At least doing so with my local copy of NJ was sufficient to enable working with the grid and to make a plot.

Before I submit a pull request, though, is there anything else I should keep in mind?

ETA: This was brought to my attention by someone at EUMETSAT, who said his particular group is trying to bring their data products up to compliance with CF 1.9 (or later).

### Code of Conduct

- [X] I agree to follow the UCAR/Unidata Code of Conduct

### PR DESCRIPTION
**Pull request by rschmunk**
## Description of Changes

Add "projection_x_angular_coordinate" and "projection_y_angular_coordinate" as acceptable axes standard names so that NJ conforms with CF-1.9 recommendation for geostationary gridded projection attributes.

Resolves https://github.com/Unidata/netcdf-java/issues/1200

## PR Checklist

- [X ] Link to any issues that the PR addresses
- [ ] Add labels
- [ ] Open as a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/)
       until ready for review
- [ ] Make sure GitHub tests pass
- [X] Mark PR as "Ready for Review"

### CODE REVIEW

**Comment by rschmunk** [comment]
Looks like spotless is getting into a fight with the auto-code-style indentation in Xcode. Sigh.

File: cdm/core/src/main/java/ucar/nc2/dataset/conv/CF1Convention.java [hunk 1]
```diff
@@ -424,13 +424,13 @@ protected AxisType getAxisType(NetcdfDataset ncDataset, VariableEnhanced v) {
         return AxisType.Lon;
       }
 
-      if (sname.equalsIgnoreCase(CF.PROJECTION_X_COORDINATE) || sname.equalsIgnoreCase(CF.GRID_LONGITUDE)
-          || sname.equalsIgnoreCase("rotated_longitude")) {
+      if (sname.equalsIgnoreCase(CF.PROJECTION_X_COORDINATE) || sname.equalsIgnoreCase(CF.PROJECTION_X_COORDINATE)
+          || sname.equalsIgnoreCase(CF.PROJECTION_X_ANG_COORDINATE) || sname.equalsIgnoreCase("rotated_longitude")) {
         return AxisType.GeoX;
```
Comment (haileyajohnson) [inline cdm/core/src/main/java/ucar/nc2/dataset/conv/CF1Convention.java:429]: missing `CF.GRID_LONGITUDE`?

File: cdm/core/src/main/java/ucar/nc2/internal/dataset/conv/CF1Convention.java [hunk 2]
```diff
@@ -482,13 +482,13 @@ public AxisType getAxisType(VariableDS.Builder vb) {
         return AxisType.Lon;
       }
 
-      if (sname.equalsIgnoreCase(CF.PROJECTION_X_COORDINATE) || sname.equalsIgnoreCase(CF.GRID_LONGITUDE)
-          || sname.equalsIgnoreCase("rotated_longitude")) {
+      if (sname.equalsIgnoreCase(CF.PROJECTION_X_COORDINATE) || sname.equalsIgnoreCase(CF.PROJECTION_X_COORDINATE)
+          || sname.equalsIgnoreCase(CF.PROJECTION_X_ANG_COORDINATE) || sname.equalsIgnoreCase("rotated_longitude")) {
         return AxisType.GeoX;
```
Comment (haileyajohnson) [inline cdm/core/src/main/java/ucar/nc2/internal/dataset/conv/CF1Convention.java:487]: Same as above

**Review by haileyajohnson — CHANGES_REQUESTED** [review]

File: cdm/core/src/main/java/ucar/nc2/internal/dataset/conv/CF1Convention.java (hunk 2 above)
Comment (rschmunk) [reply cdm/core/src/main/java/ucar/nc2/internal/dataset/conv/CF1Convention.java:487]: If you look at the source for those two classes, the case of CF.LONGITUDE ->  AxisType.Lon is handled a couple lines up.

Comment (haileyajohnson) [reply cdm/core/src/main/java/ucar/nc2/internal/dataset/conv/CF1Convention.java:487]: But what about CF.GRID_LONGITUDE -> AxisType.GeoX? The matching case for CF.GRID_LATITUDE, which is handled here

Comment (rschmunk) [reply cdm/core/src/main/java/ucar/nc2/internal/dataset/conv/CF1Convention.java:487]: Oh, wow. Looks like I missed your point.

I'm looking at the code changes I made, and it looks like there was a double copy-pasta error.

Will fix in a moment.

**Comment by rschmunk** [comment]
Dang. Had to update the pull request because I mistakenly let my local tweaks to the fatJars config leak in.

**Comment by rschmunk** [comment]
Looking like another case of the build process getting jammed up due to something _not_ in the actual PR.

**Review by haileyajohnson — APPROVED** [review]

**Comment by haileyajohnson** [comment]
thanks @rschmunk !
