### PR TITLE
Fix longitude subsetting when all longitudes are requested

### LINKED ISSUE #315: Problem getting hemispheric subset with NCSS
[Trying](https://github.com/Unidata/MetPy/discussions/2783) to download a hemispheric subset of GFS 0.5 degree data from Unidata's thredds server (looks like a 5.5 snapshot around 14 Sept 2022). The following requests:

https://thredds-dev.unidata.ucar.edu/thredds/ncss/grid/grib/NCEP/GFS/Global_0p5deg/GFS_Global_0p5deg_20221109_1200.grib2?var=Geopotential_height_isobaric&time=2022-11-09T18%3A50%3A37.350657&west=0&east=360&south=0&north=90&accept=netcdf4&addLatLon=True&vertCoord=25000

and

https://thredds-dev.unidata.ucar.edu/thredds/ncss/grid/grib/NCEP/GFS/Global_0p5deg/GFS_Global_0p5deg_20221109_1200.grib2?var=Geopotential_height_isobaric&time=2022-11-09T18%3A50%3A37.350657&west=-180&east=180&south=0&north=90&accept=netcdf4&addLatLon=True&vertCoord=25000

result in a return with a single longitude line of data. It's possible to work around this by e.g. changing 360 to 359.9. It would be really nice if instead the original queries worked like the user might expect (and did on TDS 4).

### PR DESCRIPTION
**Pull request by tdrwenski**
## Description of Changes

Fixes https://github.com/Unidata/tds/issues/315. When all longitudes are requested but not all latitudes (e.g. lon from [-180, 180]), and the longitude axis data is say {0... 360}, then the desired longitudes were getting normalized to be in the range [0, 360]. This causes the requested longitudes to be [180, 180] which results in only returning one point instead of all longitudes.

This PR uses the `allLongitude` boolean in the requested lat/lon box to fix this situation and adds a unit test for this.

Also added tests for NCSS in TDS PR: https://github.com/Unidata/tds/pull/354

## PR Checklist

- [ ] Link to any issues that the PR addresses
- [ ] Add labels
- [ ] Open as a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/)
       until ready for review
- [ ] Make sure GitHub tests pass
- [ ] Mark PR as "Ready for Review"

### CODE REVIEW

File: cdm/core/src/main/java/ucar/nc2/ft2/coverage/HorizCoordSys.java [hunk 1]
```diff
@@ -337,7 +337,7 @@ private Optional<CoverageCoordAxis> subsetLon(LatLonRect llbb, int stride) {
     double end = lonAxis.getEndValue();
 
     // use MAMath.MinMax as a container for two values, min and max
-    List<MAMath.MinMax> lonIntvs = subsetLonIntervals(wantMin, wantMax, start, end);
+    List<MAMath.MinMax> lonIntvs = subsetLonIntervals(wantMin, wantMax, start, end, llbb.containsAllLongitude());
```
Comment (haileyajohnson) [inline cdm/core/src/main/java/ucar/nc2/ft2/coverage/HorizCoordSys.java]: Can you add a comment somewhere that llbb = latlonboundingbox? I'm trying to get in the habit of labeling these things since we keep ending up going ??? about them haha

**Review by haileyajohnson — APPROVED** [review]

File: cdm/core/src/main/java/ucar/nc2/ft2/coverage/HorizCoordSys.java (hunk 1 above)
Comment (tdrwenski) [reply cdm/core/src/main/java/ucar/nc2/ft2/coverage/HorizCoordSys.java]: Yes, good point! I just updated the variable name.
